# Generated by Django 3.1.6 on 2021-02-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klassapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='comment',
            new_name='lyrics',
        ),
        migrations.RenameField(
            model_name='artist',
            old_name='name',
            new_name='song',
        ),
    ]
